### PR TITLE
A pair of log4j properties like vars

### PR DESCRIPTION
**Pull request by alvarolmedo**

### CODE REVIEW

**Comment by alvarolmedo** [comment]
Hello Tomas,

Feel free to accept this PR and merge a pair of changes in order to have the possibility to manage some log4j parameters with vars.

Comments about the code are welcome.

**Comment by deric** [comment]
Ok, much better. Could you please add newly introduced parameters to README.md?

**Comment by alvarolmedo** [comment]
Added. :)

**Comment by deric** [comment]
Thanks!

**Pull request merged**
