### PR TITLE
Proposal: extensive refactoring

### PR DESCRIPTION
**Pull request by fraenki**
Hi @deric, thanks for this module! First let me be clear with this, **I'm totally OK with you rejecting this PR**. At first I've only wanted to add support for source packages, but I felt the need to do some refactoring.

Let me try to summarize my changes...
- FEATURE: install zookeeper from archives (source packages)
- FEATURE: install arbitrary versions of ZooKeeper on any platform by using source packages
- BUGFIX: param `cfg_dir` was used instead of `zoo_dir` in `zookeeper::service`
- BUGFIX: fixed differences in default values for the same parameter (i.e. `$cleanup_sh` in `install.pp` and `init.pp`
- BUGFIX: some rspec tests were only testing the default params of a class and did not respect `$_os_overrides` from `params.pp` (i.e. used wrong service name 'zookeeper' in RedHat)
- STYLE: deduplicate parameters by completely removing them from private classes
- STYLE: use scoped variables wherever feasable
- STYLE: prefix all local variables with `_`
- STYLE: better utilize params.pp
- STYLE: resort parameters
- COMPAT: remove deprecated parameters `service_package`, `start_with`, `manage_systemd`

Benefits?
- simplified and deduplicated the code (now down to 806 lines of code, was 942 lines previously)
- removed parameters from private classes because there was no point keeping them, except for tests
- module should be easier to maintain / to extend
- test coverage is improved by testing the whole class chain everytime (not only _one_ class at a time)

Alongside these changes I've introduced a CHANGELOG and adjusted all tests to the new code.
With all these changes the module requires more testing, so I'd be glad to hear some feedback.

### CODE REVIEW

**Comment by deric** [comment]
Hey @fraenki, thanks for your contribution! First of all, it's too many changes at one time, generally I prefer smaller PR that are easier to evaluate. Have a look at [failing test](https://travis-ci.org/deric/puppet-zookeeper/jobs/153315036) it looks like some variables are undefined (`minSessionTimeout=undef`).

It looks like the archive install feature it popular, feel free to comment on #73 which implements pretty much the same. I guess I'll merge the one with nicer code :)

**Comment by deric** [comment]
Regarding the CHANGELOG, I'm trying to update [releases page](https://github.com/deric/puppet-zookeeper/releases) which is a bit more interactive than a CHANGELOG file. I don't mind having a CHANGELOG file, it would be just nice to have those two in sync. Probably we could use something [like this](https://github.com/skywinder/github-changelog-generator).

**Comment by fraenki** [comment]
@deric Regarding the failing tests, that's interesting, they're not failing for me here. I'll look into it.

```
Finished in 10.11 seconds (files took 1.27 seconds to load)
203 examples, 0 failures
```

**Comment by fraenki** [comment]
@deric I've fixed all tests. I've replaced the `majdistrelease` with the `operatingsystemmajrelease` and had to update the tests to provide this fact. Previously this was not required, because only *one* class was tested, now test coverage is improved by testing the whole class chain *everytime*.

Regarding the CHANGELOG, yes, it would be nice to automatically generate the CHANGELOG file.

**Comment by fraenki** [comment]
> First of all, it's too many changes at one time, generally I prefer smaller PR that are easier to evaluate

Yes, I totally agree. But due to the extensive debugging this wasn't feasable. That's why I've tried to summarize all changes in my initial comment. Please let me know if further explanation is required for a specific change.

**Comment by fraenki** [comment]
I've incorporated some enhancements from #73: init script for both Debian and RedHat, tests for archive installation, support for archive checksums.

**Comment by deric** [comment]
@fraenki Sorry this took so long. It looks good. But it's a lot of changes, I'd like to test the module before making another release.

**Comment by deric** [comment]
> test coverage is improved by testing the whole class chain everytime (not only one class at a time)

But it's breaking basic principle of unit testing. Not really sure whether it's really beneficial.

**Comment by fraenki** [comment]
> It looks good. But it's a lot of changes, I'd like to test the module before making another release.

Sure. Let me know if you find bugs so I can help fix them.

**Pull request merged**
