### PR TITLE
Refactored all module parameters into params.pp for easier configuration

### PR DESCRIPTION
**Pull request by danielvdende**
Centralizing all parameters makes it a lot easier to debug issues. Previously, parameter values were set per file, which often could lead to inconsistencies across files, causing annoying and difficult to solve bugs. This PR fixes this.

### CODE REVIEW

**Comment by deric** [comment]
As you can see from the automated build, this would break most of the existing code. Thanks for all the effort you've invested into the refactoring. The "params pattern" has been here since Puppet 2.6, now it is considered as deprecated, see more information:

- [http://garylarizza.com/blog/2013/12/08/when-to-hiera/](When to Hiera (Aka: How Do I Module?))
- [https://www.devco.net/archives/2013/12/09/the-problem-with-params-pp.php](The problem with params.pp)

Unfortunately there are many ways how to write a Puppet module and not all variants are supported between different Puppet versions. Hiera has been here for a while and many users rely on this functionality, we can't change this without moving to next major release. And right now I don't see any good reason why we should do this.

**Comment by danielvdende** [comment]
A number of comments I would like to make:

1. You are correct in saying that the automated build is not working at the moment. I was a bit hasty in making the PR, I should have first checked the tests to see if they'd still be ok.
2. I also agree with your remark that this change would also require some changes from users if they want to use it, as it would mean overriding parameters from hiera would mean changing the names of the parameters (i.e. parameters are now not spread out over the module, but centralized in params.pp, leading to different calls necessary from hiera.
3. I completely disagree with the opinion that hiera replaces the need for a params.pp. The goal of params.pp is to supply sane default values, which can then be overridden from hiera by users if they so desire. This is in fact the way the module currently works. There are sane defaults throughout the code, which are then overridden from hiera. The addition of params.pp only changes the place where these defaults are defined. This makes it a lot easier for users to find out what the sane defaults actually are, instead of having to look at all .pp files. Moreover, it prevents easily made mistakes, where default values actually differ across files. One thing I noticed, for instance, is that in install.pp the following sane default is used `$cleanup_sh         = '/usr/lib/zookeeper/bin/zkCleanup.sh',` whereas the default stated in init.pp is ` $cleanup_sh              = '/usr/share/zookeeper/bin/zkCleanup.sh',`. This makes it very confusing as to see what the actual value should be (I had to check in my existing install what should be the value). 
4. One of the reasons I added the params.pp is to make it easier to use a role-profile-module pattern ([link](https://puppetlabs.com/presentations/designing-puppet-rolesprofiles-pattern)). The presence of params.pp allows users to quickly see what the defaults are (without having to open all files in the module), and makes it easy to override via hiera, as the user only needs to know the parameter name, rather than also know what file it is in (i.e. should I override the parameter in `zookeeper::install` or in `zookeeper::config`. In my opinion, this shouldn't be an issue. It is considerably easier to just know the parameters that can be overridden are in `zookeeper::params`.

**Comment by mlambrichs** [comment]
Hi Deric,
my 50 cents:
- A pull request breaking an automated build, is hardly a reason to reject it. Somebody tries to improve your module, so you should respond to the reason why he/she thinks it's an improvement.
- Puppetlabs' [styleguide](https://docs.puppetlabs.com/guides/style_gui.de.html) proposes params.pp. Obviously, this is open for discussion (it's probably a matter of taste), but a style of puppet code, where params and their defaults are aggregated, gets my vote.
- The pattern has a widespread use, there are loads of examples. This is not a rock solid reason, but hey:
[50,000,000_Elvis_Fans_Can't_Be_Wrong](https://en.wikipedia.org/wiki/50,000,000_Elvis_Fans_Can't_Be_Wrong) ;-)

So, Daniel, +1

**Comment by deric** [comment]
Don't get me wrong, I'm ready to discuss the changes. But what you've sent as a PR:

  * breaks existing installations
  * doesn't bring any new feature
  * doesn't bring any improvement in performance
  * doesn't fix any existing bug

Just the first point is a good reason for me to reject the PR. Because I don't want to cause distributed propagation of errors.

`$cleanup_sh` is a good example. Debian and RedHat system use different location for placing files with the same functionality. A Puppet module should be an abstraction that takes care about these little boring differences and make sure that the package will be configured in the same way on all systems. But your PR does not fix or improve any of these. Some modules uses `params.pp` to set defaults for different distributions. One example which comes to my mind is [cloudera](https://github.com/razorsedge/puppet-cloudera/blob/master/manifests/params.pp). Or jfryman's [nginx](https://github.com/jfryman/puppet-nginx/blob/master/manifests/params.pp) - they did refactor the whole module a while ago break everything in order to refactor module's API. Still not sure we wanna do this.

@mlambrichs Puppet documentation is pretty bad, and the "standards" changes from version to version. Referring to an outdated document doesn't help. Moreover the link you've sent is dead, so I can't really comment on that.

**Comment by deric** [comment]
Closing in favour of #74. Params class included.

**Pull request closed without merging**
