### PR TITLE
Support for new distro releases

### PR DESCRIPTION
**Pull request by Hexta**
Specify initstyle for new distro releases.

### CODE REVIEW

**Comment by deric** [comment]
Thanks @Hexta, looks good to me. But we still need to fix the tests. Currently the old facts are hard-coded for test cases:
```puppet
  let(:facts) do
    {
    :operatingsystem => 'Debian',
    :osfamily => 'Debian',
    :lsbdistcodename => 'wheezy',
    :operatingsystemmajrelease => '7',
    :ipaddress => '192.168.1.1',
    :puppetversion => Puppet.version,
  }
```
There's some gem, that already offers pre-generated facts for each distribution. That might be a better way how to approach this.

**Comment by Hexta** [comment]
@deric OK. I'll do it.

**Comment by deric** [comment]
The gem is called [rspec-puppet-facts](https://github.com/mcanevet/rspec-puppet-facts). It's recommended to use it in [PDK docs](https://puppet.com/docs/pdk/1.x/pdk.html), hopefully it will stay "the right way" for a while. Let me know if you need any help.

**Comment by Hexta** [comment]
@deric Done.

**Comment by deric** [comment]
Thanks! That's quite a lot of changes, but it looks good to me.

**Pull request merged**
