### PR TITLE
Adding regex to try to set automatic ID

### PR DESCRIPTION
**Pull request by tibers**
Hostname is now parsed for last digits so `MYHOST0007` becomes `0007` for ID.

Updated readme also to warn users.

### CODE REVIEW

**Comment by tibers** [comment]
OK why doesn't the tried and true `$facts['networking']['hostname']` work here?

https://docs.puppet.com/facter/latest/core_facts.html#networking

**Comment by deric** [comment]
For backwards compatibility we need to check Puppet version, prior to Puppet 3.7 you can access the fact only via `$::hostname` (moreover it seems to be disable by default until Puppet 4.0).

**Comment by deric** [comment]
Btw. in order to make this feature usable you have to be able to generate consistently all ZooKeeper IDs at any machine. Which means that you can't use just a fact with value `MYHOST0007` because you need to know hostnames of all other ZooKeeper instances in the cluster. Each ZooKeeper has to have following list in its config:
```
server.1=zookeeper1:2888:3888
server.2=zookeeper2:2888:3888
server.3=zookeeper3:2888:3888
```
see [the template](https://github.com/deric/puppet-zookeeper/blob/master/templates/conf/zoo.cfg.erb#L32).

So you have to lookup an array of ZooKeepers (e.g. using hiera) and generate all IDs.

**Comment by tibers** [comment]
I'm going to meditate this some more.

**Pull request closed without merging**
