### PR TITLE
Add support for Modulesync

### PR DESCRIPTION
**Pull request by dhoppe**
This pull request adds a variety of Rake tasks and TravisCI tests. You also might want to add the Travis CI secret to the file ```.sync.yml```. This allows you to automatically deploy a new release to the Puppetforge. 

For further information take a look at:
* https://voxpupuli.org/docs
* https://github.com/voxpupuli/modulesync
* https://github.com/voxpupuli/modulesync_config

### CODE REVIEW

**Comment by dhoppe** [comment]
I will look at the faulty acceptance tests tomorrow.

**Comment by dhoppe** [comment]
This is looking good so far, but I think we need to do some more refactoring. For example CDH 6 is not supported and CDH 4 is end of life.
* https://travis-ci.org/github/deric/puppet-zookeeper/builds/670288632

**Comment by dhoppe** [comment]
@deric I would appreciate it, if you would merge this pull request.

**Comment by deric** [comment]
It's quite a lot of changes, sorry I didn't have earlier time to check all.

**Pull request merged**
