### PR TITLE
use puppet types

### PR DESCRIPTION
**Pull request by TheMeier**
use puppet types for all paramters and get rid of validate_*

### CODE REVIEW

**Comment by deric** [comment]
Looks good, thanks! The failing build should be removed, as it runs on Puppet 3.8. We should replace it by Puppet 5 test.

**Comment by TheMeier** [comment]
actually that failing test could be made working if there is a way to set FUTURE_PARSER=true inside the beaker VM.
I don't know (yet) how to do that.

**Comment by Wayneoween** [comment]
Seems travis ci has some issues at the moment 🤔

**Comment by TheMeier** [comment]
@deric rebased, test passing now

**Comment by deric** [comment]
Thanks a lot! These changes are target for `1.0` release.

**Pull request merged**
