### PR TITLE
CentOS7 with mesosphere repo installation fix

### PR DESCRIPTION
**Pull request by cornelf**
Description:

In the case of using Mesos on CentOS 7, proper packages for Zookeeper are made available and the service created through that installation will work fine. Everything else is configurable through hiera properties (zookeeper::user: root and zookeeper::group: root), but the service created from the template provided is breaking the Zookeeper installation from Mesosphere correct zookeeper CentOS7 packages.

* [x] only create zookeeper service if it does not exist - e.g. when zookeeper is installed from cdh5-el6; in case of using mesosphere repo which has an centos7 el7 package for zookeeper - the service is created properly and the template would break zookeeper installation if applied to replace the existing service file.

* [x] Ready for review/merge.

### CODE REVIEW

**Comment by cornelf** [comment]
All builds fail with: "Unable to find module 'puppetlabs-stdlib' on https://forgeapi.puppetlabs.com" - that looks like a librarian-puppet issue on the Travis side. Perhaps it is using some broken version of librarian-puppet.

**Comment by deric** [comment]
Looks good, thanks for your contribution!

**Comment by deric** [comment]
Same issue addresses also #26, I wondering if we can combine those approaches. Adding extra parameter seems a bit cleaner to me. What do you think?

**Comment by cornelf** [comment]
I think adding in this case "less is more". If there is a service already brought in by the packaged installed, why would you want to replace it?
If still #26 is fair approach, then I would rather combine the two like you say, having `replace => $manage_service` with default value set as 'no', giving ability to override, but not complicating the conditional.... 
I prefer to keep it simple.

**Comment by deric** [comment]
It's nice to have keep it simple, but it this case you won't be able to override the defaults. Moreover it doesn't solve the case when you want Puppet to ensure that the service is running, but you don't want to install another service configuration file.

**Comment by cornelf** [comment]
@deric - in case you want Puppet to ensure that the service is running is not inhibited on my version. On the first point - if the package installs a service for your OS, why would you want to replace that service? Before a use case for such scenario comes up/is flagged, I would keep it dry and simple.

**Pull request merged**
