### PR TITLE
Ignore CLASSPATH if systemd is used

### PR DESCRIPTION
**Pull request by dhoppe**
Fur further information take a look at:
* https://github.com/deric/puppet-zookeeper/blob/master/templates/zookeeper.service.erb#L16-L17

### CODE REVIEW

**Comment by dhoppe** [comment]
@deric Could you please take a look at this pull request and prepare a new release?

**Comment by deric** [comment]
Seems to be related to #104. Since you're up to this, can we clean up the environment file a bit?

**Comment by dhoppe** [comment]
I think this is related to #147 and should be handled in a different pull request, which will only support distributions / releases with systemd. For example there is a lot of duplicate settings like USER, GROUP, PIDDIR or PIDFILE which are not necessary or already defined by the systemd unit file.

**Comment by deric** [comment]
Right, I agree. I'll try to fix failing tests before making a release.

**Pull request merged**
